In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/smagnan/1-million-reddit-comments-from-40-subreddits/kaggle_RC_2019-05.csv

In [2]:
import pandas as pd; 
df = pd.read_csv('/kaggle/input/datasets/smagnan/1-million-reddit-comments-from-40-subreddits/kaggle_RC_2019-05.csv')
df.head(20)
df.sample(20)

,subreddit,body,controversiality,score
185143,relationship_advice,Surrey School Board and Surrey Police have bee...,0,3
880326,FortNiteBR,"it's because of packet loss, but why it does t...",0,18
518247,Market76,10k on the bolt if max lvl,0,1
598927,worldnews,I hear he has diamonds for balls and his voice...,0,2
995923,trashy,"I can't have audio rn, what's going on?",0,1
982955,trashy,Good argument ???\n\n&amp;#x200B;\n\nWhat is h...,0,1
556975,hockey,And Karlsson seems to be tapping into some oth...,0,3
323087,dankmemes,Blurry is the best,0,2
924260,todayilearned,Much Ji was earned...,0,1
39876,The_Donald,Post removed. Please post questions or discuss...,0,1
299024,Showerthoughts,Why is every letter bold but the 4 letters ‘ea...,0,2
845601,RoastMe,Honestly nahhh i could make hella money in the...,0,1
213544,memes,It was actually a spider that got the kill btw,0,3
953741,wallstreetbets,Listen. If you feel like you need to roll it a...,0,1
683708,marvelstudios,This is wrong. You can look at the Q&amp;A thr...,0,1
950865,ChapoTrapHouse,She is pretty awesome,0,3
680284,news,It's the middle east.... Just quarantine the ...,0,1
946962,Pikabu,"Шкуроходит твоя мамка, у меня на заднем дворе,...",0,1
191912,dankmemes,"If this is a dank meme, **Upvote** this commen...",0,1
829877,aww,She didn't even have time to change clothes,0,1

In [3]:
df.duplicated().sum()

np.int64(22011)

In [4]:
df = df.drop_duplicates()
print(df.shape)  # check new row count

(977989, 4)

In [5]:
print(df.columns.tolist())

['subreddit', 'body', 'controversiality', 'score']

In [6]:
df['subreddit'].str.len().describe()

count    977989.000000
mean          8.919520
std           3.965173
min           3.000000
25%           6.000000
50%           8.000000
75%          13.000000
max          19.000000
Name: subreddit, dtype: float64

In [7]:
df['body'].str.len().describe()

count    977989.000000
mean        158.421124
std         259.303086
min           7.000000
25%          42.000000
50%          79.000000
75%         167.000000
max       10106.000000
Name: body, dtype: float64

In [8]:
import re

emoji_pattern = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # emoticons
    "\U0001F300-\U0001F5FF"  # symbols & pictographs
    "\U0001F680-\U0001F6FF"  # transport & map symbols
    "\U0001F1E0-\U0001F1FF"  # flags (iOS)
    "\U00002700-\U000027BF"  # dingbats
    "\U0001F900-\U0001F9FF"  # supplemental symbols
    "\U00002600-\U000026FF"  # misc symbols
    "\U0001FA70-\U0001FAFF"  # symbols extended-A
    "\U00002B00-\U00002BFF"  # misc symbols and arrows
    "\U0001F000-\U0001F02F"  # mahjong/dominoes (rare but exists)
    "]+", flags=re.UNICODE
)

df['body'] = df['body'].astype(str).apply(lambda x: emoji_pattern.sub('', x))

In [9]:
df.sample(20)

,subreddit,body,controversiality,score
257684,dankmemes,They should watch out that we don't have a hap...,0,1
378497,worldnews,"We're Australian, not bogan Scottish twitter",0,189
34704,news,Uh. This isn't an unusual economic success at...,0,0
399706,funny,My brain also had trouble processing,0,2
960979,apexlegends,Looking forward to your feedback friend.,0,2
289297,freefolk,So right now you are theory crafting to justif...,0,0
617845,worldnews,A glitch in the matrix. This is going to be in...,0,-1
88848,relationship_advice,"Love reading these, OP. As the child of a dad ...",0,86
645115,Animemes,"Its okay, she's 18 in an alternate reality.",0,1
639084,aww,She looks cute but I can't tell because this p...,0,2
279810,unpopularopinion,You obviously don't know how taxes work. A tin...,0,1
10840,AskReddit,Take off his fucking leg at Walmart.,0,1
144225,pics,It can't be a monocle because the time is 9:32...,0,2
657015,SquaredCircle,"Vince is. Haitch is probably chill with it, he...",0,-8
426275,news,"I never said that, you're putting words behind...",0,1
677842,todayilearned,Why the fuck were marines deployed? Or was it ...,0,1
235195,marvelstudios,Hulk has now been completely useless for two c...,0,14
350419,teenagers,Rate out of 10?,0,2
796756,Pikabu,"Вот это я понимаю, хороший годный контент, а н...",0,4
381732,asoiaf,No worries! The final Jon chapter is a couple ...,0,2

In [10]:
df.to_csv('cleaned_data.csv', index=False)