In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/smagnan/1-million-reddit-comments-from-40-subreddits/kaggle_RC_2019-05.csv

In [2]:
import pandas as pd; 
df = pd.read_csv('/kaggle/input/datasets/smagnan/1-million-reddit-comments-from-40-subreddits/kaggle_RC_2019-05.csv')
df.head(20)
df.sample(20)

,subreddit,body,controversiality,score
431798,freefolk,And I'm saying her name wasn't Ingrid,0,2
944544,gonewild,Very nice! Wanna see more! 😈,0,1
827329,gaming,Looks like someone copypasted his torso over a...,0,1
31940,AskReddit,&gt; I got banned from 4-5 different subreddit...,0,1
870737,Showerthoughts,"maybe separate art from craft, so messing arou...",0,-1
43115,trashy,Is she from the U.of Texas?,0,1
180959,gameofthrones,"I agree, this does seem possible.",0,1
346998,Market76,"2* be db, 3* Bloodied Dragon with 33% VATS hit...",0,1
411353,soccer,It's all good. Spanish prisons don't fuck abou...,0,1
986136,apexlegends,hats off to you guys....\n\nplease fix the lag...,0,-1
516207,nfl,"that comes with the uniform, not the #",0,11
476460,soccer,"Thank you, at last someone explains the truth.",0,6
369017,relationship_advice,Maybe she has a suicide plan and is embarrasse...,0,66
683850,news,Had to bee an inside job.,0,1
717298,funny,OMG me too! Wasn't he a rapper from Cali too? ...,0,1
256392,teenagers,"Time stone, he reverted time",0,13
579508,nfl,Bloodys and mimosas are why people go crazy ab...,0,2
295769,RoastMe,I think its a girl that looks like a guy,0,1
181658,nba,Curry is the funnest player to watch when the ...,0,2
354398,hockey,The guy is an embarrassment to the game. Unbel...,0,1

In [3]:
df.duplicated().sum()

np.int64(22011)

In [4]:
df = df.drop_duplicates()
print(df.shape)  # check new row count

(977989, 4)

In [5]:
print(df.columns.tolist())

['subreddit', 'body', 'controversiality', 'score']

In [6]:
df['subreddit'].str.len().describe()

count    977989.000000
mean          8.919520
std           3.965173
min           3.000000
25%           6.000000
50%           8.000000
75%          13.000000
max          19.000000
Name: subreddit, dtype: float64

In [7]:
df['body'].str.len().describe()

count    977989.000000
mean        158.421124
std         259.303086
min           7.000000
25%          42.000000
50%          79.000000
75%         167.000000
max       10106.000000
Name: body, dtype: float64

In [8]:
import re

emoji_pattern = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # emoticons
    "\U0001F300-\U0001F5FF"  # symbols & pictographs
    "\U0001F680-\U0001F6FF"  # transport & map symbols
    "\U0001F1E0-\U0001F1FF"  # flags (iOS)
    "\U00002700-\U000027BF"  # dingbats
    "\U0001F900-\U0001F9FF"  # supplemental symbols
    "\U00002600-\U000026FF"  # misc symbols
    "\U0001FA70-\U0001FAFF"  # symbols extended-A
    "\U00002B00-\U00002BFF"  # misc symbols and arrows
    "\U0001F000-\U0001F02F"  # mahjong/dominoes (rare but exists)
    "]+", flags=re.UNICODE
)

df['body'] = df['body'].astype(str).apply(lambda x: emoji_pattern.sub('', x))

In [9]:
df.sample(20)

,subreddit,body,controversiality,score
247305,funny,They look fucked even in the before images,0,1
676179,Market76,"Thank you, /u/diskettejockey! You have awarded...",0,1
396596,news,"Well, I'm in the US, so don't know how the UK ...",0,1
330344,gameofthrones,better than u sugar tits,0,1
599681,marvelstudios,He still isn’t over being thrown like an insec...,0,25
810798,gaming,That's an untapped market right there,0,1
997003,trashy,Why won’t this play? Is it deleted now? ️ I wa...,0,1
732036,MortalKombat,Villains barely get chapters in MK. \n\nMK9 on...,0,2
669949,MortalKombat,"I have, I approach scorpion with jumping kicks...",0,1
217454,gameofthrones,They need to take the Assassin's Creed Odyssey...,0,1
298043,todayilearned,Most medieval peasants could get their hands o...,0,9
413001,teenagers,Many of us aren't still in school and aren't a...,0,1
904115,movies,Never to old for The Goonies,0,1010
305429,FortNiteBR,"**Unfortunately, we've had to remove your post...",0,1
833615,SquaredCircle,"Bayley, but send her over with Raw for UK tour...",0,6
878838,FortNiteBR,"Hell yeah, instant destroy and instant mats!",0,100
890418,videos,"No, in this system there were only a handful o...",0,7
753488,gonewild,O.m.g. That’s an awesome pose and view.,0,2
618138,relationship_advice,Reasons why this is all a terrible idea: you n...,0,1
822585,pics,For everyone this is in finnish liquor store!!,0,1